# Project Information
#
site_name: Machine Learning Systems Design
site_url: https://ahayasic.github.io/machine-learning-systems-design
site_author: Alisson Hayasi da Costa
# site_description:


# Repository
#
repo_name: ahayasic/machine-learning-systems-design
repo_url: https://github.com/ahayasic/machine-learning-systems-design
edit_uri: ""


# Copyright
#
copyright: Copyright &copy; 2021 Alisson Hayasi da Costa


# Configuration
#
theme:
  name: material
  language: pt

  # Features
  features:
    - content.code.annotate
    # - content.tabs.link
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    # - navigation.expand
    - navigation.top
    # - header.autohide
    - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

  # Colors
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Trocar para Modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Trocar para Modo Claro

  # Font
  font:
    text: Source Sans Pro
    code: DM Mono
    font: false
  # favicon:
  icon:
    repo: fontawesome/brands/github


# Plugins
#
plugins:
  - search


# Extras
#
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ahayasic/
    - icon: fontawesome/brands/github
      link: https://github.com/ahayasic
    - icon: fontawesome/solid/globe
      link: https://ahayasic.github.io/

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css


# Extensions
#
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ahayasic
      repo: machine-learning-systems-design
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree
#
nav:
  - Início: index.md
  - Sobre: index.md
  - Teoria:
    - Design de Sistemas de ML & MLOps: introducing_mlops.md
    - Qualidades Desejáveis em Projetos de ML: ml_systems_desired_qualities.md
    - Considerações de Projeto:
      - Ciclo de Vida de um Projeto de ML: project_planning/index.md
      - Desafios no Desenvolvimento de Modelos: project_planning/index.md
      - IA Centrada em Dados: project_planning/index.md
      - CRISP-ML(Q): project_planning/index.md
    - Manipulação de Dados:
      - Coleta de Dados: data_management/index.md
      - Processamento de Dados: data_management/index.md
    - Treinamento:
      - Treinamento de Modelos Supervisionados: training/index.md
    - Avaliação:
      - Avaliação de Modelos: evaluation/index.md
    - Implantação:
      - Estratégias de Implantação de Modelos: deployment/index.md
    - Servindo Modelos:
      - Estratégias para Servir Modelos: serving/model_serving_strategies.md
      - (Going Deeper) Model as a Service: serving/index.md
      - (Going Deeper) Model as a Dependency: serving/index.md
      - (Going Deeper) Model as a Pré-Computação: serving/index.md
      - (Going Deeper) Modelo sob Demanda: serving/index.md
      - (Going Deeper) Federated Learning: serving/index.md
    - Monitoramento:
      - Monitoramento de Modelos de ML: monitoring/index.md
    - Práticas Essenciais de MLOps:
      - Versionamento: mlops/index.md
      - Rastreamento de Experimentos: mlops/index.md
      - Automação de Pipelines de ML: mlops/index.md
      - Testes Automatizados: mlops/index.md
      - Feature Stores: mlops/index.md
      - Model Registry: mlops/index.md
    - Boas Práticas em ML:
      - Dado: index.md
      - Modelo: index.md
      - Código: index.md
  - Prática: index.md
  - Referências: index.md
